services:
  postgresql:
    image: docker.io/postgres:17-alpine
    restart: unless-stopped
    volumes:
      - /mnt/postgres/postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    command:
      - -c
      - wal_level=logical
