version: "3.8"

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backoffice-dariordal-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./vendor:/var/www/html/vendor
    networks:
      - backoffice-dariordal-network
    env_file:
      - .env

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: backoffice-dariordal-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx-stg.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - backoffice-dariordal-network
    depends_on:
      - app

networks:
  backoffice-dariordal-network:
    driver: bridge
