name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCE_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to GCE
      run: |
        ssh ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_HOST }} << 'EOF'
          cd /home/YOUR_FOLDER/app
          git pull origin main
          docker compose down
          docker compose up -d --build
        EOF
